# Generated by Django 5.2.1 on 2025-08-27 03:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_options_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-ativo', 'dia_pagamento', '-data_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['endereco', 'numero'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='agencia',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='anuente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuentes', to='core.cliente', verbose_name='Anuente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='banco',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='celular',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cep',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='chave_pix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='conta_corrente',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='documento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='endereco',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado_civil',
            field=models.CharField(blank=True, choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viuvo', 'Viúvo(a)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nacionalidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome',
            field=models.CharField(default=0, max_length=100, verbose_name='Nome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_fantasia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='pix_modalidade',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatorio', 'Chave Aleatória')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='poupanca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='profissao',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='razao_social',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regime_casamento',
            field=models.CharField(blank=True, choices=[('comunhao_total', 'Comunhão Total de Bens'), ('comunhao_parcial', 'Comunhão Parcial de Bens'), ('separacao_total', 'Separação Total de Bens')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Representante Legal', 'tipo_pessoa': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_representados', to='core.cliente', verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='rg_rne',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG/RNE'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador(a)', 'Fiador(a)'), ('Representante Legal', 'Representante Legal')], default=0, max_length=20, verbose_name='Tipo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_pessoa',
            field=models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='apolice',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='carencia_dias',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Carência (dias)'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausula_12meses',
            field=models.BooleanField(default=False, verbose_name='12 meses?'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(default=0, verbose_name='Fim'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(default=0, verbose_name='Início'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='dia_pagamento',
            field=models.IntegerField(default=0, verbose_name='Dia de Pagamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='contratos/documentos/', verbose_name='Documentos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fator_reajuste',
            field=models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], default=0, max_length=5, verbose_name='Fator de Reajuste'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='garantia',
            field=models.CharField(choices=[('FIADOR', 'Fiador'), ('CAUCAO', 'Caução'), ('SEGURO_FIANCA', 'Seguro Fiança'), ('CAPITALIZACAO', 'Capitalização'), ('SEM_GARANTIA', 'Sem Garantia')], default=0, max_length=50, verbose_name='Garantia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='historico_aluguel',
            field=models.JSONField(blank=True, default=dict, verbose_name='Histórico de Valores'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='multa_contratual',
            field=models.CharField(choices=[('3MPR', '3M Pró Rata'), ('3MF', '3M Flat'), ('6MPR', '6M Pró Rata'), ('6MF', '6M Flat')], default=0, max_length=20, verbose_name='Multa Contratual'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='seguradora',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_pagamento',
            field=models.CharField(choices=[('pacote', 'Pacote'), ('despesas_separadas', 'Despesas Separadas')], default='despesas_separadas', max_length=50, verbose_name='Tipo de Aluguel'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='tipo_taxa',
            field=models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Fixo (R$)')], default=0, max_length=50, verbose_name='Tipo de Taxa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Base'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_caucao',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_seguro_incendio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor do Seguro'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_taxa_administracao_fixo',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Adm - R$'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_taxa_administracao_percentual',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Adm - %'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='vencimento_seguro_incendio',
            field=models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='bairro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(default=0, max_length=10, verbose_name='CEP'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='cidade',
            field=models.CharField(default=0, max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='comgas',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comgás'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='endereco',
            field=models.CharField(default=0, max_length=255, verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='enel',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enel'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='estado',
            field=models.CharField(default=0, max_length=2, verbose_name='Estado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='iptu',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='IPTU'),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(default=0, max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='sabesp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sabesp'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiador', to='core.cliente', verbose_name='Fiador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_imovel', to='core.imovel', verbose_name='Imóvel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inquilino',
            field=models.ManyToManyField(related_name='contratos_inquilino', to='core.cliente', verbose_name='Inquilinos'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proprietario',
            field=models.ManyToManyField(related_name='contratos_proprietario', to='core.cliente', verbose_name='Proprietários'),
        ),
    ]
