# Generated by Django 5.2.1 on 2025-08-27 04:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_cliente_options_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='data_fim',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Início'),
        ),
    ]
