# Generated by Django 4.2.19 on 2025-03-09 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador(a)', 'Fiador(a)')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nacionalidade')),
                ('profissao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Profissão')),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viuvo', 'Viúvo(a)')], max_length=20, null=True)),
                ('regime_casamento', models.CharField(blank=True, choices=[('comunhao_total', 'Comunhão Total de Bens'), ('comunhao_parcial', 'Comunhão Parcial de Bens'), ('separacao_total', 'Separação Total de Bens')], max_length=20, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Telefone')),
                ('codigo_internacional_celular', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código Internacional (Celular)')),
                ('celular', models.CharField(blank=True, max_length=15, null=True, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('pix_modalidade', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatorio', 'Chave Aleatória')], max_length=20, null=True, verbose_name='Modalidade PIX')),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True, verbose_name='Chave PIX')),
                ('banco', models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco')),
                ('agencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Agência')),
                ('conta_corrente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Conta Corrente')),
                ('poupanca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Poupança')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('anuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisimob.cliente', verbose_name='Anuente')),
            ],
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('iptu', models.CharField(blank=True, max_length=14, null=True, verbose_name='IPTU')),
                ('comgas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comgás')),
                ('sabesp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sabesp')),
                ('enel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enel')),
            ],
        ),
        migrations.CreateModel(
            name='IndiceInflacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50, verbose_name='Nome do Índice')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Índice')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('tipo_contrato', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True)),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('carencia_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Carência')),
                ('fator_reajuste', models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=5, verbose_name='Reajuste')),
                ('multa_contratual', models.CharField(choices=[('3MPR', '3M Pró Rata'), ('3MF', '3M Flat'), ('6MPR', '6M Pró Rata'), ('6MF', '6M Flat')], max_length=20, verbose_name='Multa Contratual')),
                ('tipo_pagamento', models.CharField(choices=[('pacote', 'Pacote'), ('despesas_separadas', 'Despesas Separadas')], default='despesas_separadas', max_length=50, verbose_name='Tipo de Aluguel')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Aluguel')),
                ('valor_pacote', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Pacote')),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Condomínio')),
                ('valor_iptu', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='IPTU')),
                ('valor_outros', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Outros')),
                ('tipo_taxa', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Fixo (R$)')], max_length=50, verbose_name='Tipo de Taxa')),
                ('valor_taxa_administracao_percentual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='Adm - %')),
                ('valor_taxa_administracao_fixo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Adm - R$')),
                ('dia_pagamento', models.IntegerField(verbose_name='Dia de Pagamento')),
                ('garantia', models.CharField(choices=[('fiador', 'Fiador'), ('caucao', 'Caução'), ('seguro_fianca', 'Seguro Fiança'), ('capitalizacao', 'Capitalização'), ('sem_garantia', 'Sem Garantia')], max_length=50, verbose_name='Garantia')),
                ('fiador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiador')),
                ('valor_caucao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Caução')),
                ('valor_segfi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Fiança')),
                ('apolice_segfi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice Fiança')),
                ('seg_segfi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Fiança')),
                ('valor_cap', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Capitalização')),
                ('apolice_cap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice Capitalização')),
                ('seg_cap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Capitalização')),
                ('clausula_12meses', models.BooleanField(default=False, verbose_name='Cláusula de 12 Meses?')),
                ('seguradora_incendio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora')),
                ('apolice_incendio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice')),
                ('valor_seguro', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Seguro')),
                ('vencimento_seguro', models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='contratos/documentos/', verbose_name='Documentos')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_imovel', to='sisimob.imovel')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_inquilino', to='sisimob.cliente')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_proprietario', to='sisimob.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.IntegerField()),
                ('ano_referencia', models.IntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisimob.contrato')),
            ],
            options={
                'ordering': ['-ano_referencia', '-mes_referencia'],
            },
        ),
    ]
