# Generated by Django 4.2.19 on 2025-05-07 03:45

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pessoa', models.CharField(choices=[('F', 'Pessoa Física'), ('J', 'Pessoa Jurídica')], default='F', max_length=1, verbose_name='Tipo de Pessoa')),
                ('tipo', models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador(a)', 'Fiador(a)'), ('Representante Legal', 'Representante Legal')], max_length=20, verbose_name='Tipo')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('razao_social', models.CharField(blank=True, max_length=255, null=True, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('CPF', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('rg_rne', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG/RNE')),
                ('nacionalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('profissao', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_civil', models.CharField(blank=True, choices=[('Solteiro', 'Solteiro(a)'), ('Casado', 'Casado(a)'), ('Divorciado', 'Divorciado(a)'), ('Viuvo', 'Viúvo(a)')], max_length=20, null=True)),
                ('regime_casamento', models.CharField(blank=True, choices=[('comunhao_total', 'Comunhão Total de Bens'), ('comunhao_parcial', 'Comunhão Parcial de Bens'), ('separacao_total', 'Separação Total de Bens')], max_length=30, null=True)),
                ('telefone', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('pix_modalidade', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('aleatorio', 'Chave Aleatória')], max_length=20, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=100, null=True)),
                ('banco', models.CharField(blank=True, max_length=100, null=True)),
                ('agencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conta_corrente', models.CharField(blank=True, max_length=100, null=True)),
                ('poupanca', models.CharField(blank=True, max_length=100, null=True)),
                ('cep', models.CharField(max_length=10)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=10)),
                ('complemento', models.CharField(blank=True, max_length=100, null=True)),
                ('bairro', models.CharField(blank=True, max_length=100, null=True)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=2)),
                ('documento', models.CharField(blank=True, max_length=100, null=True)),
                ('asaas_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anuentes', to='sisimob.cliente', verbose_name='Anuente')),
                ('representante_legal', models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Representante Legal', 'tipo_pessoa': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_representados', to='sisimob.cliente', verbose_name='Representante Legal')),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('clausula_12meses', models.BooleanField(default=False, verbose_name='12 meses?')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo de Contrato')),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Fim')),
                ('carencia_dias', models.IntegerField(blank=True, default=0, null=True, verbose_name='Carência (dias)')),
                ('fator_reajuste', models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=5, verbose_name='Fator de Reajuste')),
                ('multa_contratual', models.CharField(choices=[('3MPR', '3M Pró Rata'), ('3MF', '3M Flat'), ('6MPR', '6M Pró Rata'), ('6MF', '6M Flat')], max_length=20, verbose_name='Multa Contratual')),
                ('tipo_pagamento', models.CharField(choices=[('pacote', 'Pacote'), ('despesas_separadas', 'Despesas Separadas')], default='despesas_separadas', max_length=50, verbose_name='Tipo de Aluguel')),
                ('valor_base', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Base')),
                ('tipo_taxa', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Fixo (R$)')], max_length=50, verbose_name='Tipo de Taxa')),
                ('valor_taxa_administracao_percentual', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True, verbose_name='Adm - %')),
                ('valor_taxa_administracao_fixo', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Adm - R$')),
                ('dia_pagamento', models.IntegerField(verbose_name='Dia de Pagamento')),
                ('garantia', models.CharField(choices=[('FIADOR', 'Fiador'), ('CAUCAO', 'Caução'), ('SEGURO_FIANCA', 'Seguro Fiança'), ('CAPITALIZACAO', 'Capitalização'), ('SEM_GARANTIA', 'Sem Garantia')], max_length=50, verbose_name='Garantia')),
                ('valor_caucao', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução')),
                ('seguradora', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora')),
                ('apolice', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice')),
                ('valor_seguro_incendio', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor do Seguro')),
                ('vencimento_seguro_incendio', models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='contratos/documentos/', verbose_name='Documentos')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('historico_aluguel', models.JSONField(default=dict, verbose_name='Histórico de Aluguel')),
                ('data_ultimo_reajuste', models.DateField(blank=True, null=True, verbose_name='Data do último reajuste')),
                ('fiador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiador', to='sisimob.cliente', verbose_name='Fiador')),
            ],
            options={
                'ordering': ['-ativo', 'dia_pagamento', '-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=10, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('iptu', models.CharField(blank=True, max_length=14, null=True, verbose_name='IPTU')),
                ('comgas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Comgás')),
                ('sabesp', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sabesp')),
                ('enel', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enel')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),

            ],
        ),
        
        migrations.AddField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_imovel', to='sisimob.imovel', verbose_name='Imóvel'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='inquilino',
            field=models.ManyToManyField(related_name='contratos_inquilino', to='sisimob.cliente', verbose_name='Inquilinos'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='proprietario',
            field=models.ManyToManyField(related_name='contratos_proprietario', to='sisimob.cliente', verbose_name='Proprietários'),
        ),
    ]
