# Generated by Django 4.2.19 on 2025-05-08 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('10_dias', '10 Dias Úteis'), ('3_dias', '3 Dias Úteis'), ('vencimento', 'No Dia do Vencimento')], max_length=20)),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes', to='sisimob.cobranca')),
            ],
            options={
                'unique_together': {('cobranca', 'tipo')},
            },
        ),
    ]
