# Generated by Django 4.2.19 on 2025-03-11 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranca',
            options={},
        ),
        migrations.AddField(
            model_name='cobranca',
            name='data_repasse',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='status_repasse',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('repassado', 'Repassado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='cobranca',
            unique_together={('contrato', 'mes_referencia', 'ano_referencia')},
        ),
    ]
