# Generated by Django 3.1.12 on 2025-02-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador(a)', 'Fiador(a)')], max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador', 'Fiador(a)')], max_length=20, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('tipo_contrato', models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True)),
                ('data_inicio', models.DateField(verbose_name='Início')),
                ('data_fim', models.DateField(verbose_name='Final')),
                ('carencia_dias', models.IntegerField(verbose_name='Carência')),
                ('fator_reajuste', models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=5, verbose_name='Reajuste')),
                ('multa_contratual', models.CharField(choices=[('3MPR', '3M Pró Rata'), ('3MF', '3M Flat'), ('6MPR', '6M Pró Rata'), ('6MF', '6M Flat')], max_length=20, verbose_name='Multa Contratual')),
                ('tipo_pagamento', models.CharField(choices=[('Despesas_Separadas', 'Despesas Separadas'), ('Pacote', 'Pacote')], max_length=50, verbose_name='Tipo de Aluguel')),
                ('valor_aluguel', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Aluguel')),
                ('valor_pacote', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Pacote')),
                ('valor_condominio', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Condomínio')),
                ('valor_iptu', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='IPTU')),
                ('valor_outros', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Outros')),
                ('tipo_taxa', models.CharField(choices=[('percentual', 'Percentual (%)'), ('fixo', 'Fixo (R$)')], max_length=50, verbose_name='Tipo de Taxa')),
                ('valor_taxa_administracao_percentual', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Adm - %')),
                ('valor_taxa_administracao_fixo', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Adm - R$')),
                ('dia_pagamento', models.IntegerField(verbose_name='Dia de Pagamento')),
                ('garantia', models.CharField(choices=[('fiador', 'Fiador'), ('caucao', 'Caução'), ('seguro_fianca', 'Seguro Fiança'), ('capitalizacao', 'Capitalização'), ('sem_garantia', 'Sem Garantia')], max_length=50, verbose_name='Garantia')),
                ('fiador', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fiador')),
                ('valor_caucao', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Caução')),
                ('valor_segfi', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Fiança')),
                ('apolice_segfi', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice Fiança')),
                ('seg_segfi', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Fiança')),
                ('valor_cap', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor Capitalização')),
                ('apolice_cap', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice Capitalização')),
                ('seg_cap', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Capitalização')),
                ('clausula_12meses', models.BooleanField(default=False, verbose_name='Cláusula de 12 Meses?')),
                ('seguradora_incendio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora')),
                ('apolice_incendio', models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice')),
                ('valor_seguro', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Valor do Seguro')),
                ('vencimento_seguro', models.DateField(blank=True, null=True, verbose_name='Vencimento do Seguro')),
                ('documentos', models.FileField(blank=True, null=True, upload_to='documentos/', verbose_name='Documentos')),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_imovel', to='sisimob.imovel', verbose_name='Imóvel')),
                ('inquilino', models.ForeignKey(limit_choices_to={'tipo': 'Inquilino'}, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_inquilino', to='sisimob.cliente', verbose_name='Inquilino')),
                ('proprietario', models.ForeignKey(limit_choices_to={'tipo': 'Proprietário(a)'}, on_delete=django.db.models.deletion.CASCADE, related_name='contratos_proprietario', to='sisimob.cliente', verbose_name='Proprietário')),
            ],
        ),
    ]
