# Generated by Django 4.2.19 on 2025-05-22 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0002_lembreteenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor Base'),
        ),
    ]
