# Generated by Django 4.2.19 on 2025-03-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0002_alter_cobranca_options_cobranca_data_repasse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='status_repasse',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('repassado', 'Repassado')], default='pendente', max_length=10),
        ),
    ]
