# Generated by Django 3.1.12 on 2025-02-24 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0002_auto_20250219_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='carencia_dias',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Carência'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador', 'Fiador(a)')], max_length=20, null=True, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='IndiceInflacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=10, verbose_name='Tipo de Índice')),
                ('ano', models.IntegerField(verbose_name='Ano')),
                ('mes', models.IntegerField(verbose_name='Mês')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (%)')),
            ],
            options={
                'unique_together': {('tipo', 'ano', 'mes')},
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(default='PENDENTE', max_length=20)),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('numero_referencia', models.CharField(max_length=20)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisimob.contrato')),
            ],
            options={
                'unique_together': {('contrato', 'vencimento')},
            },
        ),
    ]
