# Generated by Django 3.1.12 on 2025-02-27 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0003_auto_20250223_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='CobrancaAluguel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status_pagamento', models.CharField(choices=[('PAGO', 'Pago'), ('PENDENTE', 'Pendente'), ('ATRASADO', 'Atrasado')], default='PENDENTE', max_length=10)),
                ('status_repasse', models.CharField(choices=[('REPASSADO', 'Repassado'), ('PENDENTE', 'Pendente')], default='PENDENTE', max_length=10)),
                ('data_repasse', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='sisimob.contrato')),
            ],
        ),
        migrations.DeleteModel(
            name='Cobranca',
        ),
    ]
