# Generated by Django 4.2.19 on 2025-05-22 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0003_contrato_valor_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_aluguel',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_pacote',
        ),
    ]
