# Generated by Django 4.2.19 on 2025-03-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0003_alter_cobranca_status_repasse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='data_pagamento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Pagamento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_repasse',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Repasse'),
        ),
    ]
