# Generated by Django 4.2.19 on 2025-05-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0004_remove_contrato_valor_aluguel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='data_ultimo_reajuste',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='historico_aluguel',
        ),
    ]
