# Generated by Django 4.2.19 on 2025-03-19 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0004_alter_cobranca_data_pagamento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranca',
            options={'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='apolice_incendio',
            new_name='apolice',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='seguradora_incendio',
            new_name='seguradora',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='valor_seguro',
            new_name='valor_seguro_incendio',
        ),
        migrations.RenameField(
            model_name='contrato',
            old_name='vencimento_seguro',
            new_name='vencimento_seguro_incendio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='apolice_cap',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='apolice_segfi',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='clausula_12meses',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='seg_cap',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='seg_segfi',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_cap',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_segfi',
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='ano_referencia',
            field=models.IntegerField(verbose_name='Ano de Referência'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='sisimob.contrato'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_vencimento',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='mes_referencia',
            field=models.IntegerField(verbose_name='Mês de Referência'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status_repasse',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('repassado', 'Repassado'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status do Repasse'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Cobrança'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiador', to='sisimob.cliente'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='garantia',
            field=models.CharField(choices=[('FIADOR', 'Fiador'), ('CAUCAO', 'Caução'), ('SEGURO_FIANCA', 'Seguro Fiança'), ('CAPITALIZACAO', 'Capitalização'), ('SEM_GARANTIA', 'Sem Garantia')], max_length=50, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo'),
        ),
    ]
