# Generated by Django 4.2.19 on 2025-06-06 07:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0005_remove_contrato_data_ultimo_reajuste_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cobranca',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='contrato',
        ),
        migrations.DeleteModel(
            name='IndiceInflacao',
        ),
        migrations.RemoveField(
            model_name='lancamentocontacorrente',
            name='proprietario',
        ),
        migrations.AlterUniqueTogether(
            name='lembreteenviado',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lembreteenviado',
            name='cobranca',
        ),
        migrations.RemoveField(
            model_name='movimentoconta',
            name='contrato',
        ),
        migrations.RemoveField(
            model_name='movimentoconta',
            name='proprietario',
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-ativo', 'dia_pagamento', '-data_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='imovel',
            options={'ordering': ['endereco', 'numero'], 'verbose_name': 'Imóvel', 'verbose_name_plural': 'Imóveis'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contrato',
            name='historico_aluguel',
            field=models.JSONField(blank=True, default=dict, verbose_name='Histórico de Valores'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='imovel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Cobranca',
        ),
        migrations.DeleteModel(
            name='Despesa',
        ),
        migrations.DeleteModel(
            name='LancamentoContaCorrente',
        ),
        migrations.DeleteModel(
            name='LembreteEnviado',
        ),
        migrations.DeleteModel(
            name='MovimentoConta',
        ),
    ]
