# Generated by Django 4.2.19 on 2025-03-21 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0005_alter_cobranca_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='CPF',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
