# Generated by Django 4.2.19 on 2025-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0006_cliente_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rg_rne',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG/RNE'),
        ),
    ]
