# Generated by Django 4.2.19 on 2025-03-23 20:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0007_cliente_rg_rne'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='valor_condominio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_iptu',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_outros',
        ),
        migrations.AddField(
            model_name='contrato',
            name='historico_aluguel',
            field=models.JSONField(default=dict, verbose_name='Histórico de Aluguel'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='rg_rne',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='RG/RNE'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='sisimob.contrato', verbose_name='Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='carencia_dias',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Carência (dias)'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fator_reajuste',
            field=models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=5, verbose_name='Fator de Reajuste'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fiador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contratos_fiador', to='sisimob.cliente', verbose_name='Fiador'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_imovel', to='sisimob.imovel', verbose_name='Imóvel'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='inquilino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_inquilino', to='sisimob.cliente', verbose_name='Inquilino'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos_proprietario', to='sisimob.cliente', verbose_name='Proprietário'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_contrato',
            field=models.CharField(blank=True, choices=[('residencial', 'Residencial'), ('comercial', 'Comercial'), ('nao_residencial', 'Não-Residencial')], max_length=20, null=True, verbose_name='Tipo de Contrato'),
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('iptu', 'IPTU'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Despesa')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('numero_parcelas', models.IntegerField(verbose_name='Número de Parcelas')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Término')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas', to='sisimob.contrato', verbose_name='Contrato')),
            ],
        ),
        migrations.CreateModel(
            name='ContaCorrenteProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Saldo Atual')),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_corrente', to='sisimob.contrato', verbose_name='Contrato')),
            ],
        ),
    ]
