# Generated by Django 4.2.19 on 2025-03-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0008_remove_contrato_valor_condominio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='cobranca_referencia',
            field=models.CharField(blank=True, help_text='Ex: 01/2023 para IPTU ou nome do condomínio', max_length=20, null=True, verbose_name='Cobrança de Referência'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='periodicidade',
            field=models.CharField(choices=[('mensal', 'Mensal'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unica', 'Única')], default='mensal', max_length=20, verbose_name='Periodicidade'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('iptu', 'IPTU'), ('condominio', 'Condomínio'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Despesa'),
        ),
    ]
