# Generated by Django 4.2.19 on 2025-03-25 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0009_despesa_cobranca_referencia_despesa_periodicidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('repasse', 'Repasse'), ('iptu', 'IPTU'), ('condominio', 'Condomínio'), ('manutencao', 'Manutenção'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Despesa'),
        ),
    ]
