# Generated by Django 4.2.19 on 2025-03-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0010_alter_despesa_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
