# Generated by Django 4.2.19 on 2025-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0011_alter_contrato_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='percentual_repassado',
            field=models.DecimalField(decimal_places=2, default=100.0, help_text='Percentual da despesa que será repassado ao inquilino', max_digits=5, verbose_name='Percentual repassado'),
        ),
        migrations.AddField(
            model_name='despesa',
            name='repassar_inquilino',
            field=models.BooleanField(default=False, help_text='Marcar se esta despesa deve ser repassada ao inquilino', verbose_name='Repassar ao inquilino?'),
        ),
    ]
