# Generated by Django 4.2.19 on 2025-03-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0012_despesa_percentual_repassado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='paga',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('inquilino', 'Inquilino'), ('imobiliaria', 'Imobiliaria')], default=0, max_length=20, verbose_name='Quem paga?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição'),
        ),
    ]
