# Generated by Django 4.2.19 on 2025-03-27 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0013_despesa_paga_alter_despesa_descricao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-data_inicio']},
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='data_fim',
        ),
        migrations.RemoveField(
            model_name='despesa',
            name='repassar_inquilino',
        ),
    ]
