# Generated by Django 4.2.19 on 2025-03-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0014_alter_contrato_options_remove_despesa_data_fim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='paga',
            field=models.CharField(choices=[('proprietario', 'Proprietário'), ('inquilino', 'Inquilino'), ('imobiliaria', 'Imobiliária')], max_length=20, verbose_name='Quem paga?'),
        ),
    ]
