# Generated by Django 4.2.19 on 2025-03-27 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0015_alter_despesa_paga'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='repassar_inquilino',
            field=models.BooleanField(default=False, help_text='Marcar se esta despesa deve ser repassada ao inquilino', verbose_name='Repassar ao inquilino?'),
        ),
    ]
