# Generated by Django 4.2.19 on 2025-03-27 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0016_despesa_repassar_inquilino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='status_repasse',
            field=models.CharField(blank=True, choices=[('pendente', 'Pendente'), ('repassado', 'Repassado')], default='pendente', max_length=20, null=True),
        ),
    ]
