# Generated by Django 4.2.19 on 2025-03-27 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0017_alter_cobranca_status_repasse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranca',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='cobranca',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='sisimob.contrato'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Recebida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10, verbose_name='Status do Pagamento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status_repasse',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('repassado', 'Repassada'), ('cancelado', 'Cancelado')], default='pendente', max_length=10, verbose_name='Status do Repasse'),
        ),
    ]
