# Generated by Django 4.2.19 on 2025-03-29 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0018_alter_cobranca_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaAvulsa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('parcelas', models.PositiveIntegerField()),
                ('data_inicio', models.DateField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_avulsas', to='sisimob.contrato')),
            ],
        ),
    ]
