# Generated by Django 4.2.19 on 2025-03-29 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0019_despesaavulsa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='mes_referencia',
            field=models.CharField(max_length=7),
        ),
    ]
