# Generated by Django 4.2.19 on 2025-03-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0020_alter_cobranca_mes_referencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='ano_referencia',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='mes_referencia',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
