# Generated by Django 4.2.19 on 2025-03-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0021_alter_cobranca_ano_referencia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesaavulsa',
            name='contrato',
        ),
        migrations.AlterField(
            model_name='despesa',
            name='numero_parcelas',
            field=models.PositiveIntegerField(default=1, verbose_name='Número de Parcelas'),
        ),
        migrations.DeleteModel(
            name='ContaCorrenteProprietario',
        ),
        migrations.DeleteModel(
            name='DespesaAvulsa',
        ),
    ]
