# Generated by Django 4.2.19 on 2025-03-29 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0022_remove_despesaavulsa_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='repassar_inquilino',
        ),
    ]
