# Generated by Django 4.2.19 on 2025-03-30 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0023_remove_despesa_repassar_inquilino'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='is_base_calculo_administracao',
            field=models.BooleanField(default=False, verbose_name='É base para cálculo da administração?'),
        ),
    ]
