# Generated by Django 4.2.19 on 2025-04-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0024_despesa_is_base_calculo_administracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='asaas_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ID Asaas'),
        ),
    ]
