# Generated by Django 4.2.19 on 2025-04-03 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0025_cliente_asaas_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='asaas_boleto_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='asaas_codigo_barras',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='asaas_payment_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='asaas_pix_copia_cola',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='asaas_pix_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
