# Generated by Django 4.2.19 on 2025-04-03 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sisimob', '0026_cobranca_asaas_boleto_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='inquilino',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Inquilino'),
            preserve_default=False,
        ),
    ]
