# Generated by Django 4.2.19 on 2025-04-03 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0027_cobranca_inquilino'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobranca',
            name='inquilino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisimob.cliente'),
        ),
    ]
