# Generated by Django 4.2.19 on 2025-04-04 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0028_alter_cobranca_inquilino'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
