# Generated by Django 4.2.19 on 2025-04-04 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0029_cobranca_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('repasse', 'Repasse Efetuado')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sisimob.contrato')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisimob.cliente')),
            ],
            options={
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoContaCorrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('repasse', 'Repasse')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisimob.cliente')),
            ],
        ),
    ]
