# Generated by Django 4.2.19 on 2025-04-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0030_movimentoconta_lancamentocontacorrente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_internacional_celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='documento',
        ),
        migrations.AddField(
            model_name='cliente',
            name='documentos',
            field=models.FileField(blank=True, null=True, upload_to='clientes/documentos/', verbose_name='Documentos'),
        ),
    ]
