# Generated by Django 4.2.19 on 2025-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0031_remove_cliente_codigo_internacional_celular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='is_recorrente',
            field=models.BooleanField(default=False, help_text='Marque para despesas que se repetem periodicamente como condomínio', verbose_name='É despesa recorrente?'),
        ),
        migrations.AlterField(
            model_name='despesa',
            name='tipo',
            field=models.CharField(choices=[('repasse', 'Repasse'), ('iptu', 'IPTU'), ('condominio', 'Condomínio'), ('manutencao', 'Manutenção'), ('despesa_recorrente', 'Despesa Recorrente'), ('outros', 'Outros')], max_length=20, verbose_name='Tipo de Despesa'),
        ),
    ]
