# Generated by Django 4.2.19 on 2025-04-12 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0031_cliente_cnpj_cliente_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='codigo_internacional_celular',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='inscricao_estadual',
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.ForeignKey(blank=True, limit_choices_to={'tipo': 'Representante Legal', 'tipo_pessoa': 'F'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_representados', to='sisimob.cliente', verbose_name='Representante Legal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('Proprietario', 'Proprietário(a)'), ('Inquilino', 'Inquilino(a)'), ('Anuente', 'Anuente'), ('Fiador(a)', 'Fiador(a)'), ('Representante Legal', 'Representante Legal')], max_length=20, verbose_name='Tipo'),
        ),
    ]
