# Generated by Django 4.2.19 on 2025-04-13 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0032_remove_cliente_codigo_internacional_celular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reajuste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_reajuste', models.DateField()),
                ('fator_calculado', models.DecimalField(decimal_places=4, max_digits=6)),
                ('fator_aprovado', models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True)),
                ('valor_calculado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_aprovado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('aprovado', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reajustes', to='sisimob.contrato')),
            ],
        ),
    ]
