# Generated by Django 4.2.19 on 2025-04-30 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0032_despesa_is_recorrente_alter_despesa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='data_ultimo_reajuste',
            field=models.DateField(blank=True, null=True, verbose_name='Data do último reajuste'),
        ),
    ]
