# Generated by Django 4.2.19 on 2025-04-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0033_contrato_data_ultimo_reajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobranca',
            name='lembrete_0_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='lembrete_10_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='lembrete_3_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
