# Generated by Django 4.2.19 on 2025-04-14 00:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0033_reajuste'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='apolice_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='apolice_segfi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='clausula_12meses',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='seg_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='seg_segfi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='valor_segfi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Caução'),
        ),
    ]
