# Generated by Django 4.2.19 on 2025-04-14 04:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0034_contrato_apolice_cap_contrato_apolice_segfi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='apolice_incendio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='seguradora_incendio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='apolice_cap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apólice Capitalização'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='apolice_segfi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apólice Seguro Fiança'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clausula_12meses',
            field=models.BooleanField(default=False, verbose_name='Clausula 12 Meses'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='seg_cap',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Capitalização'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='seg_segfi',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Seguro Fiança'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_cap',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Capitalização'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_segfi',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Seguro Fiança'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_seguro_incendio',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True, verbose_name='Valor Seguro Incendio'),
        ),
    ]
