# Generated by Django 4.2.19 on 2025-04-14 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0036_contrato_valor_aluguel_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='apolice_incendio',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apólice Incêndio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='clausula_12meses',
            field=models.BooleanField(default=False, verbose_name='Cláusula 12 Meses'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='dia_pagamento',
            field=models.IntegerField(blank=True, null=True, verbose_name='Dia de Pagamento'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fator_reajuste',
            field=models.CharField(blank=True, choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M')], max_length=5, null=True, verbose_name='Fator de Reajuste'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='garantia',
            field=models.CharField(blank=True, choices=[('FIADOR', 'Fiador'), ('CAUCAO', 'Caução'), ('SEGURO_FIANCA', 'Seguro Fiança'), ('CAPITALIZACAO', 'Capitalização'), ('SEM_GARANTIA', 'Sem Garantia')], max_length=50, null=True, verbose_name='Garantia'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='multa_contratual',
            field=models.CharField(blank=True, choices=[('3MPR', '3M Pró Rata'), ('3MF', '3M Flat'), ('6MPR', '6M Pró Rata'), ('6MF', '6M Flat')], max_length=20, null=True, verbose_name='Multa Contratual'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='seguradora_incendio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Seguradora Incêndio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo_taxa',
            field=models.CharField(blank=True, choices=[('percentual', 'Percentual (%)'), ('fixo', 'Fixo (R$)')], max_length=50, null=True, verbose_name='Tipo de Taxa'),
        ),
    ]
