# Generated by Django 4.2.19 on 2025-04-15 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0037_alter_contrato_apolice_incendio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='historico_aluguel',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Histórico de Aluguel'),
        ),
    ]
