# Generated by Django 4.2.19 on 2025-04-15 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0038_alter_contrato_historico_aluguel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contrato',
            name='apolice',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='seguradora',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='tipo',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_seguro_incendio',
        ),
        migrations.RemoveField(
            model_name='contrato',
            name='valor_seguro_incendio_currency',
        ),
    ]
