# Generated by Django 4.2.19 on 2025-04-17 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0040_cobranca_valor_currency_despesa_valor_total_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LembreteEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_antecipacao', models.IntegerField()),
                ('data_envio', models.DateField(auto_now_add=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sisimob.cobranca')),
            ],
            options={
                'unique_together': {('cobranca', 'dias_antecipacao')},
            },
        ),
    ]
