# Generated by Django 4.2.19 on 2025-04-19 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0041_lembreteenviado'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='valor_por_parcela',
            field=models.BooleanField(default=False, help_text='Se marcado, o valor digitado será considerado o valor de cada parcela.', verbose_name='Valor informado é por parcela?'),
        ),
    ]
