# Generated by Django 4.2.19 on 2025-04-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0042_despesa_valor_por_parcela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='numero_parcelas',
            field=models.PositiveIntegerField(blank=True, help_text='Deixe em branco para despesas recorrentes sem parcelas definidas.', null=True, verbose_name='Número de Parcelas'),
        ),
    ]
