# Generated by Django 4.2.19 on 2025-04-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0043_alter_despesa_numero_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='despesa_recorrente',
            field=models.BooleanField(default=False, help_text='Marque para despesas mensais contínuas, como condomínio.', verbose_name='Despesa recorrente?'),
        ),
    ]
