# Generated by Django 4.2.19 on 2025-05-20 00:27

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sisimob', '0002_lembreteenviado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor_aluguel', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor base do aluguel', max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total da cobrança (aluguel + despesas)', max_digits=10)),
                ('data_vencimento', models.DateField()),
                ('data_emissao', models.DateField(auto_now_add=True)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Recebida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=10)),
                ('asaas_id', models.CharField(blank=True, help_text='ID da cobrança no Asaas', max_length=100, null=True)),
                ('boleto_url', models.URLField(blank=True, null=True)),
                ('pix_copia_cola', models.TextField(blank=True, null=True)),
                ('pix_qrcode', models.TextField(blank=True, null=True)),
                ('pix_url', models.URLField(blank=True, null=True)),
                ('codigo_barras', models.CharField(blank=True, max_length=150, null=True)),
                ('fatura_url', models.URLField(blank=True, null=True)),
                ('gateway_status', models.CharField(blank=True, max_length=30, null=True)),
                ('lembrete_10_enviado', models.BooleanField(default=False)),
                ('lembrete_3_enviado', models.BooleanField(default=False)),
                ('lembrete_0_enviado', models.BooleanField(default=False)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_financeiro', to='sisimob.contrato')),
                ('inquilino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cobrancas_recebidas', to='sisimob.cliente')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-ano_referencia', '-mes_referencia'],
            },
        ),
        migrations.CreateModel(
            name='TipoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('icone', models.CharField(blank=True, max_length=50, null=True)),
                ('cor', models.CharField(blank=True, max_length=20, null=True)),
                ('is_recorrente_padrao', models.BooleanField(default=False)),
                ('is_base_calculo_admin_padrao', models.BooleanField(default=False)),
                ('ordem_exibicao', models.PositiveSmallIntegerField(default=99)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Despesa',
                'verbose_name_plural': 'Tipos de Despesas',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='SaldoProprietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('proprietario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saldo_financeiro', to='sisimob.cliente')),
            ],
            options={
                'verbose_name': 'Saldo de Proprietário',
                'verbose_name_plural': 'Saldos de Proprietários',
            },
        ),
        migrations.CreateModel(
            name='MovimentoConta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito'), ('repasse', 'Repasse Efetuado')], max_length=10)),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('data_referencia', models.DateField(blank=True, null=True)),
                ('origem_simplificada', models.BooleanField(default=False, help_text='Indica se foi um lançamento manual/simplificado')),
                ('contrato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiro', to='sisimob.contrato')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos_financeiro', to='sisimob.cliente')),
            ],
            options={
                'verbose_name': 'Movimento de Conta',
                'verbose_name_plural': 'Movimentos de Conta',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='IndiceInflacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IPCA', 'IPC-A'), ('IGPM', 'IGP-M'), ('INPC', 'INPC'), ('OUTRO', 'Outro Índice')], max_length=50, verbose_name='Nome do Índice')),
                ('valor', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Valor do Índice')),
                ('data_referencia', models.DateField(verbose_name='Data de Referência')),
                ('acumulado_12_meses', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Acumulado 12 meses')),
                ('fonte', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fonte da Informação')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
            ],
            options={
                'verbose_name': 'Índice de Inflação',
                'verbose_name_plural': 'Índices de Inflação',
                'ordering': ['-data_referencia'],
                'indexes': [models.Index(fields=['tipo', 'data_referencia'], name='financeiro__tipo_4803c1_idx')],
                'unique_together': {('tipo', 'data_referencia')},
            },
        ),
        migrations.CreateModel(
            name='LembreteEnviado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail'), ('sms', 'SMS')], max_length=20)),
                ('dias_antes_vencimento', models.IntegerField(help_text='Quantos dias antes do vencimento este lembrete foi enviado')),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('falha', 'Falha')], default='enviado', max_length=20)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cobranca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lembretes_enviados', to='financeiro.cobranca')),
            ],
            options={
                'verbose_name': 'Lembrete de Cobrança Enviado',
                'verbose_name_plural': 'Lembretes de Cobrança Enviados',
                'ordering': ['-data_envio'],
                'indexes': [models.Index(fields=['cobranca', 'dias_antes_vencimento'], name='financeiro__cobranc_8124a6_idx'), models.Index(fields=['tipo', 'status'], name='financeiro__tipo_3eb170_idx')],
            },
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paga_por', models.CharField(choices=[('proprietario', 'Proprietário'), ('inquilino', 'Inquilino'), ('imobiliaria', 'Imobiliária')], max_length=20)),
                ('numero_parcelas', models.PositiveIntegerField(default=1)),
                ('periodicidade', models.CharField(choices=[('mensal', 'Mensal'), ('bimestral', 'Bimestral'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual'), ('unica', 'Unica')], default='mensal', max_length=20)),
                ('data_inicio', models.DateField()),
                ('data_fim_prevista', models.DateField(blank=True, null=True)),
                ('data_encerramento', models.DateField(blank=True, null=True)),
                ('cobranca_referencia', models.CharField(blank=True, max_length=20, null=True)),
                ('percentual_repassado', models.DecimalField(decimal_places=2, default=100, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_base_calculo_administracao', models.BooleanField(default=False)),
                ('is_recorrente', models.BooleanField(default=False)),
                ('is_ativa', models.BooleanField(default=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='despesas/comprovantes/')),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_financeiro', to='sisimob.contrato')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='financeiro.tipodespesa')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-data_inicio', 'tipo'],
                'indexes': [models.Index(fields=['contrato', 'data_inicio'], name='financeiro__contrat_7daf39_idx'), models.Index(fields=['is_ativa', 'tipo'], name='financeiro__is_ativ_46f67c_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['contrato', 'status'], name='financeiro__contrat_72f21e_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['mes_referencia', 'ano_referencia'], name='financeiro__mes_ref_901a59_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['data_vencimento'], name='financeiro__data_ve_555eec_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cobranca',
            unique_together={('contrato', 'mes_referencia', 'ano_referencia')},
        ),
    ]
