# Generated by Django 4.2.19 on 2025-05-20 21:39

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('periodicidade', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='mensal', max_length=20)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('dias_apos_recebimento', models.PositiveSmallIntegerField(default=2)),
                ('percentual_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxa_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor_minimo_repasse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Repasse',
                'verbose_name_plural': 'Políticas de Repasse',
                'ordering': ['-ativa', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Repasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_desconto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('valor_taxa_admin', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateField()),
                ('data_efetivacao', models.DateField(blank=True, null=True)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('efetuado', 'Efetuado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('tipo', models.CharField(choices=[('automatico', 'Automático'), ('manual', 'Manual')], default='automatico', max_length=20)),
                ('metodo_pagamento', models.CharField(blank=True, choices=[('pix', 'PIX'), ('transferencia', 'Transferência Bancária'), ('ted', 'TED'), ('doc', 'DOC'), ('cheque', 'Cheque'), ('dinheiro', 'Dinheiro'), ('outros', 'Outros')], max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='repasses/comprovantes/')),
                ('cobranca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repasses_cobranca', to='financeiro.cobranca')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reprepasses_financeiroasses', to='core.contrato')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses_recebidos', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Repasse',
                'verbose_name_plural': 'Repasses',
                'ordering': ['-ano_referencia', '-mes_referencia', '-data_prevista'],
            },
        ),
        migrations.CreateModel(
            name='ReajusteAluguel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_reajustado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fator_aplicado', models.DecimalField(decimal_places=2, help_text='Percentual aplicado, ex: 6.78', max_digits=5)),
                ('indice_utilizado', models.CharField(choices=[('IPCA', 'IPCA'), ('IGPM', 'IGP-M'), ('INPC', 'INPC'), ('MANUAL', 'Manual')], default='MANUAL', max_length=20)),
                ('data_reajuste', models.DateField(help_text='Data em que o novo valor passa a valer')),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reajustes', to='core.contrato')),
            ],
            options={
                'verbose_name': 'Reajuste de Aluguel',
                'verbose_name_plural': 'Reajustes de Aluguel',
                'ordering': ['-data_reajuste'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoRepasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_agendada', models.DateField()),
                ('data_processamento', models.DateTimeField(blank=True, null=True)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('processando', 'Processando'), ('concluido', 'Concluído'), ('falha', 'Falha'), ('cancelado', 'Cancelado')], default='agendado', max_length=20)),
                ('detalhes_processamento', models.TextField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_repasse', to='core.contrato')),
                ('politica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.politicarepasse')),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos_repasse', to='core.cliente')),
            ],
            options={
                'verbose_name': 'Agendamento de Repasse',
                'verbose_name_plural': 'Agendamentos de Repasse',
                'ordering': ['data_agendada', 'status'],
            },
        ),
    ]
