# Generated by Django 4.2.19 on 2025-05-21 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_politicarepasse_repasse_reajustealuguel_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'ordering': ['nome'], 'verbose_name': 'Tipo de Despesa', 'verbose_name_plural': 'Tipos de Despesas'},
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='cor',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='icone',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='is_base_calculo_admin_padrao',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='is_recorrente_padrao',
        ),
        migrations.RemoveField(
            model_name='tipodespesa',
            name='ordem_exibicao',
        ),
    ]
