# Generated by Django 4.2.19 on 2025-05-22 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0003_alter_tipodespesa_options_remove_tipodespesa_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reajustealuguel',
            name='data_reajuste',
            field=models.DateField(help_text='Data a partir da qual o novo valor entra em vigor'),
        ),
        migrations.AlterField(
            model_name='reajustealuguel',
            name='fator_aplicado',
            field=models.DecimalField(decimal_places=2, help_text='Percentual aplicado, ex: 6.78 para 6,78%', max_digits=5),
        ),
        migrations.AlterUniqueTogether(
            name='reajustealuguel',
            unique_together={('contrato', 'data_reajuste')},
        ),
    ]
