# Generated by Django 4.2.19 on 2025-05-30 11:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_reajustealuguel_data_reajuste_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranca',
            options={'ordering': ['-ano_referencia', '-mes_referencia', '-data_vencimento'], 'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
        migrations.AddField(
            model_name='cobranca',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobranca',
            name='integrada_asaas',
            field=models.BooleanField(default=False, help_text='Indica se foi integrada com Asaas'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações internas', null=True),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['status', 'data_vencimento'], name='financeiro__status_df3f81_idx'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['integrada_asaas'], name='financeiro__integra_dc98c8_idx'),
        ),
    ]
