# Generated by Django 4.2.19 on 2025-06-04 01:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sisimob', '0005_remove_contrato_data_ultimo_reajuste_and_more'),
        ('financeiro', '0005_melhorias_cobranca'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asaasintegracao',
            options={'verbose_name': 'Integração Asaas', 'verbose_name_plural': 'Integrações Asaas'},
        ),
        migrations.AlterModelOptions(
            name='cobranca',
            options={'ordering': ['-ano_referencia', '-mes_referencia', '-data_vencimento'], 'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='financeiro__contrat_72f21e_idx',
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='financeiro__mes_ref_901a59_idx',
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='financeiro__data_ve_555eec_idx',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='asaas_id',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='boleto_url',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='fatura_url',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='gateway_status',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='inquilino',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='pix_copia_cola',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='pix_qrcode',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='pix_url',
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='data_ultima_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='envio_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='envio_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='fatura_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='formas_pagamento',
            field=models.JSONField(default=list, help_text="Formas de pagamento habilitadas ['BOLETO', 'PIX', etc]"),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='pix_qrcode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='webhooks_recebidos',
            field=models.JSONField(default=list, help_text='Log dos webhooks recebidos do Asaas'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cobranca',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Observações internas', null=True),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='asaas_id',
            field=models.CharField(help_text='ID da cobrança no Asaas', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='cobranca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asaas_integracao', to='financeiro.cobranca'),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='gateway_status',
            field=models.CharField(blank=True, help_text='Status retornado pelo Asaas', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='ano_referencia',
            field=models.PositiveSmallIntegerField(help_text='Ano de referência da cobrança', validators=[django.core.validators.MinValueValidator(2020), django.core.validators.MaxValueValidator(2030)]),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='contrato',
            field=models.ForeignKey(help_text='Contrato ao qual esta cobrança se refere', on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_financeiro', to='sisimob.contrato'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, help_text='Data de criação da cobrança'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data em que o pagamento foi recebido', null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_vencimento',
            field=models.DateField(help_text='Data limite para pagamento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='descricao',
            field=models.TextField(blank=True, help_text='Descrição detalhada da cobrança', null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='mes_referencia',
            field=models.PositiveSmallIntegerField(help_text='Mês ao qual se refere esta cobrança', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Recebida'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada')], default='pendente', max_length=20),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status_detalhes',
            field=models.JSONField(blank=True, default=dict, help_text='Detalhes adicionais sobre o status'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor_aluguel',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor base do aluguel', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='valor_despesas',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total das despesas incluídas', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddIndex(
            model_name='asaasintegracao',
            index=models.Index(fields=['asaas_id'], name='idx_asaas_id'),
        ),
        migrations.AddIndex(
            model_name='asaasintegracao',
            index=models.Index(fields=['gateway_status'], name='idx_gateway_status'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['status', 'data_vencimento'], name='idx_status_vencimento'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['contrato', 'mes_referencia', 'ano_referencia'], name='idx_contrato_periodo'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['ano_referencia', 'mes_referencia'], name='idx_periodo'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['data_emissao'], name='idx_data_emissao'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['data_pagamento'], name='idx_data_pagamento'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['status'], name='idx_status'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(check=models.Q(('valor_aluguel__gt', 0)), name='valor_aluguel_positivo'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(check=models.Q(('valor_total__gte', models.F('valor_aluguel'))), name='valor_total_maior_igual_aluguel'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(check=models.Q(('valor_despesas__gte', 0)), name='valor_despesas_nao_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(check=models.Q(('mes_referencia__gte', 1), ('mes_referencia__lte', 12)), name='mes_referencia_valido'),
        ),
    ]
