# Generated by Django 4.2.19 on 2025-06-05 10:55

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0006_alter_asaasintegracao_options_alter_cobranca_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoliticaRepasseContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ativa', models.BooleanField(default=True)),
                ('periodicidade', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='mensal', max_length=20)),
                ('tipo_dias', models.CharField(choices=[('corridos', 'Dias Corridos'), ('uteis', 'Dias Úteis')], default='uteis', max_length=10)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, help_text='Dia do mês para repasse mensal (1-31)', null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], help_text='Dia da semana para repasse semanal', null=True)),
                ('dias_apos_recebimento', models.PositiveSmallIntegerField(default=2, help_text='Dias para aguardar após recebimento')),
                ('percentual_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxa_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor_minimo_repasse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxa_admin_personalizada', models.DecimalField(blank=True, decimal_places=2, help_text='Taxa específica para este contrato (deixe vazio para usar padrão)', max_digits=5, null=True)),
                ('considerar_feriados', models.BooleanField(default=True, help_text='Considerar feriados no cálculo de dias úteis')),
                ('antecipar_fds_feriados', models.BooleanField(default=True, help_text='Antecipar repasse se data cair em final de semana/feriado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('contrato', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='politica_repasse', to='core.contrato')),
            ],
            options={
                'verbose_name': 'Política de Repasse do Contrato',
                'verbose_name_plural': 'Políticas de Repasse dos Contratos',
                'ordering': ['-data_atualizacao'],
            },
        ),
        migrations.CreateModel(
            name='PoliticaRepasseGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('ativa', models.BooleanField(default=True)),
                ('periodicidade', models.CharField(choices=[('diaria', 'Diária'), ('semanal', 'Semanal'), ('quinzenal', 'Quinzenal'), ('mensal', 'Mensal')], default='mensal', max_length=20)),
                ('tipo_dias', models.CharField(choices=[('corridos', 'Dias Corridos'), ('uteis', 'Dias Úteis')], default='uteis', max_length=10)),
                ('dia_mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dia_semana', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Segunda-feira'), (2, 'Terça-feira'), (3, 'Quarta-feira'), (4, 'Quinta-feira'), (5, 'Sexta-feira'), (6, 'Sábado'), (7, 'Domingo')], null=True)),
                ('dias_apos_recebimento', models.PositiveSmallIntegerField(default=2)),
                ('percentual_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('taxa_adiantamento', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('valor_minimo_repasse', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('taxa_admin_padrao', models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=5)),
                ('considerar_feriados', models.BooleanField(default=True)),
                ('antecipar_fds_feriados', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Política de Repasse Global',
                'verbose_name_plural': 'Políticas de Repasse Globais',
                'ordering': ['-ativa', 'nome'],
            },
        ),
        migrations.RemoveField(
            model_name='agendamentorepasse',
            name='politica',
        ),
        migrations.AlterField(
            model_name='repasse',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repasses_contrato', to='core.contrato'),
        ),
        migrations.DeleteModel(
            name='PoliticaRepasse',
        ),
        migrations.AddField(
            model_name='agendamentorepasse',
            name='politica_contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.politicarepassecontrato'),
        ),
        migrations.AddField(
            model_name='agendamentorepasse',
            name='politica_global',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='financeiro.politicarepasseglobal'),
        ),
    ]
