# Generated by Django 4.2.19 on 2025-06-06 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_politicarepassecontrato_politicarepasseglobal_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cobranca',
            options={'ordering': ['-data_vencimento', '-ano_referencia', '-mes_referencia'], 'verbose_name': 'Cobrança', 'verbose_name_plural': 'Cobranças'},
        ),
    ]
