# Generated by Django 4.2.19 on 2025-06-10 00:25

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_cobranca_contrato_remove_cobranca_inquilino_and_more'),
        ('financeiro', '0008_alter_cobranca_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cobranca',
            name='valor_aluguel_positivo',
        ),
        migrations.RemoveConstraint(
            model_name='cobranca',
            name='valor_total_maior_igual_aluguel',
        ),
        migrations.RemoveConstraint(
            model_name='cobranca',
            name='valor_despesas_nao_negativo',
        ),
        migrations.RemoveIndex(
            model_name='asaasintegracao',
            name='idx_asaas_id',
        ),
        migrations.RemoveIndex(
            model_name='asaasintegracao',
            name='idx_gateway_status',
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='idx_periodo',
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='idx_data_emissao',
        ),
        migrations.RemoveIndex(
            model_name='cobranca',
            name='idx_data_pagamento',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='envio_email',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='envio_whatsapp',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='fatura_url',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='formas_pagamento',
        ),
        migrations.RemoveField(
            model_name='asaasintegracao',
            name='webhooks_recebidos',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='lembrete_0_enviado',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='lembrete_10_enviado',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='lembrete_3_enviado',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='status_detalhes',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='valor_aluguel',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='valor_despesas',
        ),
        migrations.RemoveField(
            model_name='cobranca',
            name='valor_total',
        ),
        migrations.AddField(
            model_name='cobranca',
            name='criada_automaticamente',
            field=models.BooleanField(default=True, help_text='Se foi criada pelo processo automático'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='detalhes_calculo',
            field=models.JSONField(default=dict, help_text='Detalhes de como o valor foi calculado (valor_base + despesas)'),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='numero_cobranca',
            field=models.CharField(blank=True, help_text='Número único da cobrança', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='cobranca',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Valor total da cobrança (contrato.valor_base + despesas)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='asaas_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='gateway_status',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='contrato',
            field=models.ForeignKey(help_text='Contrato base desta cobrança', on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_financeiro', to='core.contrato'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_emissao',
            field=models.DateField(auto_now_add=True, help_text='Data de criação'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_pagamento',
            field=models.DateField(blank=True, help_text='Data do pagamento (quando paga)', null=True),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='data_vencimento',
            field=models.DateField(help_text='Data de vencimento'),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='descricao',
            field=models.TextField(blank=True, default=0, help_text='Descrição detalhada da cobrança'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='mes_referencia',
            field=models.PositiveSmallIntegerField(help_text='Mês de referência da cobrança', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='observacoes',
            field=models.TextField(blank=True, default=0, help_text='Observações internas'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cobranca',
            name='status',
            field=models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('paga', 'Paga'), ('atrasada', 'Atrasada'), ('cancelada', 'Cancelada'), ('parcial', 'Pago Parcial')], default='rascunho', max_length=20),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['numero_cobranca'], name='idx_numero_cobranca'),
        ),
        migrations.AddIndex(
            model_name='cobranca',
            index=models.Index(fields=['data_vencimento'], name='idx_vencimento'),
        ),
        migrations.AddConstraint(
            model_name='cobranca',
            constraint=models.CheckConstraint(check=models.Q(('valor__gt', 0)), name='valor_positivo'),
        ),
    ]
