# Generated by Django 4.2.19 on 2025-06-22 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0009_remove_cobranca_valor_aluguel_positivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasintegracao',
            name='codigo_barras',
            field=models.TextField(blank=True, null=True, verbose_name='Código de Barras'),
        ),
    ]
