# Generated by Django 4.2.19 on 2025-06-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0010_asaasintegracao_codigo_barras'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasintegracao',
            name='linha_digitavel',
            field=models.TextField(blank=True, help_text='Linha digitável do boleto (identificationField)', null=True, verbose_name='Linha Digitável'),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='nosso_numero',
            field=models.CharField(blank=True, help_text='Nosso número do boleto', max_length=50, null=True, verbose_name='Nosso Número'),
        ),
        migrations.AlterField(
            model_name='asaasintegracao',
            name='codigo_barras',
            field=models.TextField(blank=True, help_text='Código de barras numérico do boleto', null=True, verbose_name='Código de Barras'),
        ),
    ]
