# Generated by Django 4.2.19 on 2025-06-29 05:03

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('financeiro', '0011_asaasintegracao_linha_digitavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepasseDetalhado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_bruto_total', models.DecimalField(decimal_places=2, help_text='Valor total da cobrança (o que o inquilino pagou)', max_digits=12)),
                ('valor_taxa_admin_total', models.DecimalField(decimal_places=2, help_text='Total de taxa administrativa descontada', max_digits=12)),
                ('valor_liquido_repasse', models.DecimalField(decimal_places=2, help_text='Valor líquido a ser repassado ao proprietário', max_digits=12)),
                ('composicao_detalhada', models.JSONField(default=dict, help_text='Detalhamento de como o valor foi composto e calculado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_prevista', models.DateField()),
                ('data_efetivacao', models.DateField(blank=True, null=True)),
                ('mes_referencia', models.PositiveSmallIntegerField()),
                ('ano_referencia', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('efetuado', 'Efetuado'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='repasses/comprovantes/')),
            ],
            options={
                'verbose_name': 'Repasse Detalhado',
                'verbose_name_plural': 'Repasses Detalhados',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AlterModelOptions(
            name='tipodespesa',
            options={'ordering': ['categoria', 'nome'], 'verbose_name': 'Tipo de Despesa', 'verbose_name_plural': 'Tipos de Despesas'},
        ),
        migrations.AddField(
            model_name='despesa',
            name='incidencia_taxa_admin',
            field=models.CharField(choices=[('sim', 'Sim - Tem incidência de taxa administrativa'), ('nao', 'Não - Isenta de taxa administrativa'), ('parcial', 'Parcial - Apenas parte tem incidência')], default='nao', help_text='Define se esta despesa tem incidência de taxa administrativa', max_length=10),
        ),
        migrations.AddField(
            model_name='despesa',
            name='percentual_com_incidencia',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Para incidência parcial: % do valor que tem incidência (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='despesa',
            name='taxa_admin_especifica',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taxa específica para esta despesa (deixe vazio para usar padrão do contrato)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='categoria',
            field=models.CharField(choices=[('operacional', 'Operacional'), ('manutencao', 'Manutenção'), ('melhorias', 'Melhorias'), ('impostos', 'Impostos/Taxas'), ('servicos', 'Serviços'), ('outros', 'Outros')], default='outros', max_length=30),
        ),
        migrations.AddField(
            model_name='tipodespesa',
            name='incidencia_taxa_admin_padrao',
            field=models.BooleanField(default=False, help_text='Por padrão, despesas deste tipo têm incidência de taxa administrativa?'),
        ),
        migrations.AddIndex(
            model_name='despesa',
            index=models.Index(fields=['incidencia_taxa_admin', 'paga_por'], name='financeiro__inciden_446910_idx'),
        ),
        migrations.AddField(
            model_name='repassedetalhado',
            name='cobranca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='financeiro.cobranca'),
        ),
        migrations.AddField(
            model_name='repassedetalhado',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.contrato'),
        ),
        migrations.AddField(
            model_name='repassedetalhado',
            name='proprietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
    ]
