# Generated by Django 4.2.19 on 2025-08-20 20:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0012_repassedetalhado_alter_tipodespesa_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='percentual_com_incidencia',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Para incidência parcial: % do valor que tem incidência (0-100%)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
