# Generated by Django 5.2.1 on 2025-08-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0013_alter_despesa_percentual_com_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asaasintegracao',
            name='envio_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='envio_whatsapp',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='fatura_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='formas_pagamento',
            field=models.JSONField(default=list, help_text="Formas de pagamento habilitadas ['BOLETO', 'PIX', etc]"),
        ),
        migrations.AddField(
            model_name='asaasintegracao',
            name='webhooks_recebidos',
            field=models.JSONField(default=list, help_text='Log dos webhooks recebidos do Asaas'),
        ),
    ]
